-- À exécuter une fois dans Supabase > SQL Editor avant d’utiliser le formulaire.
-- Boîte de réception des propositions de liens familiaux envoyées depuis le site.
-- Les visiteurs peuvent uniquement créer une demande via la fonction dédiée ;
-- seules les personnes inscrites dans public.superadmins peuvent les consulter
-- ou les traiter.

create table if not exists public.family_link_requests (
  id bigint generated by default as identity primary key,
  child_id text not null,
  child_name text not null,
  parent_id text not null,
  parent_name text not null,
  message text not null default '',
  status text not null default 'pending'
    check (status in ('pending', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  constraint family_link_requests_distinct_students check (trim(child_id) <> trim(parent_id))
);

alter table public.family_link_requests
  add column if not exists email_claimed_at timestamptz,
  add column if not exists email_sent_at timestamptz;

-- Garde-fou simple contre un envoi massif d'e-mails depuis le formulaire public.
create table if not exists public.family_link_request_email_rate_limit (
  id boolean primary key default true check (id is true),
  window_started_at timestamptz not null default now(),
  sent_count integer not null default 0 check (sent_count >= 0)
);
alter table public.family_link_request_email_rate_limit enable row level security;
revoke all on public.family_link_request_email_rate_limit from anon, authenticated;

create index if not exists family_link_requests_status_created_idx
  on public.family_link_requests (status, created_at desc);

alter table public.family_link_requests enable row level security;
revoke all on public.family_link_requests from anon, authenticated;

create or replace function public.submit_family_link_request(
  p_child_id text,
  p_child_name text,
  p_parent_id text,
  p_parent_name text,
  p_message text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  inserted_request public.family_link_requests%rowtype;
  clean_message text := coalesce(trim(p_message), '');
begin
  if nullif(trim(p_child_id), '') is null
    or nullif(trim(p_parent_id), '') is null
    or nullif(trim(p_child_name), '') is null
    or nullif(trim(p_parent_name), '') is null
    or trim(p_child_id) = trim(p_parent_id) then
    raise exception 'Choisis deux étudiants différents.' using errcode = '22023';
  end if;

  if length(trim(p_child_id)) > 120
    or length(trim(p_parent_id)) > 120
    or length(trim(p_child_name)) > 200
    or length(trim(p_parent_name)) > 200
    or length(clean_message) > 1500 then
    raise exception 'La demande est trop longue.' using errcode = '22023';
  end if;

  insert into public.family_link_requests (
    child_id, child_name, parent_id, parent_name, message
  ) values (
    trim(p_child_id), trim(p_child_name), trim(p_parent_id), trim(p_parent_name), clean_message
  ) returning * into inserted_request;

  return jsonb_build_object(
    'id', inserted_request.id,
    'created_at', inserted_request.created_at
  );
end;
$$;

create or replace function public.list_family_link_requests()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if auth.uid() is null or not exists (
    select 1 from public.superadmins s where s.user_id = auth.uid()
  ) then
    raise exception 'Accès réservé au superadmin.' using errcode = '42501';
  end if;

  select coalesce(
    jsonb_agg(to_jsonb(r) order by (r.status = 'pending') desc, r.created_at desc),
    '[]'::jsonb
  ) into result
  from public.family_link_requests r;

  return result;
end;
$$;

create or replace function public.update_family_link_request(
  p_request_id bigint,
  p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated_request public.family_link_requests%rowtype;
begin
  if auth.uid() is null or not exists (
    select 1 from public.superadmins s where s.user_id = auth.uid()
  ) then
    raise exception 'Accès réservé au superadmin.' using errcode = '42501';
  end if;

  if p_status is null or p_status not in ('pending', 'resolved', 'dismissed') then
    raise exception 'Statut de demande invalide.' using errcode = '22023';
  end if;

  update public.family_link_requests r
    set status = p_status,
        reviewed_at = case when p_status = 'pending' then null else now() end,
        reviewed_by = case when p_status = 'pending' then null else auth.uid() end
    where r.id = p_request_id
    returning * into updated_request;

  if not found then
    raise exception 'Cette demande n’existe plus.' using errcode = 'P0002';
  end if;

  return to_jsonb(updated_request);
end;
$$;

-- Réservé à la fonction Edge qui envoie l'e-mail : une seule notification
-- peut être en cours pour une proposition donnée.
create or replace function public.claim_family_link_request_email(p_request_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  claimed_request public.family_link_requests%rowtype;
  emails_in_window integer;
begin
  if auth.role() is distinct from 'service_role' then
    raise exception 'Accès réservé au service d’envoi.' using errcode = '42501';
  end if;

  update public.family_link_requests r
    set email_claimed_at = now()
    where r.id = p_request_id
      and r.email_sent_at is null
      and (r.email_claimed_at is null or r.email_claimed_at < now() - interval '10 minutes')
    returning * into claimed_request;

  if not found then
    return null;
  end if;

  insert into public.family_link_request_email_rate_limit as limits (
    id, window_started_at, sent_count
  ) values (true, now(), 1)
  on conflict (id) do update
    set window_started_at = case
          when limits.window_started_at <= now() - interval '1 hour' then now()
          else limits.window_started_at
        end,
        sent_count = case
          when limits.window_started_at <= now() - interval '1 hour' then 1
          else limits.sent_count + 1
        end
  returning sent_count into emails_in_window;

  if emails_in_window > 10 then
    update public.family_link_requests r
      set email_claimed_at = null
      where r.id = p_request_id and r.email_sent_at is null;
    raise exception 'Limite horaire de notifications atteinte.' using errcode = 'P0001';
  end if;

  return to_jsonb(claimed_request);
end;
$$;

create or replace function public.mark_family_link_request_email_sent(p_request_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.role() is distinct from 'service_role' then
    raise exception 'Accès réservé au service d’envoi.' using errcode = '42501';
  end if;

  update public.family_link_requests r
    set email_sent_at = now(),
        email_claimed_at = null
    where r.id = p_request_id
      and r.email_sent_at is null
      and r.email_claimed_at is not null;

  return found;
end;
$$;

create or replace function public.release_family_link_request_email(p_request_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.role() is distinct from 'service_role' then
    raise exception 'Accès réservé au service d’envoi.' using errcode = '42501';
  end if;

  update public.family_link_requests r
    set email_claimed_at = null
    where r.id = p_request_id and r.email_sent_at is null;

  return found;
end;
$$;

revoke all on function public.submit_family_link_request(text, text, text, text, text) from public;
revoke all on function public.list_family_link_requests() from public;
revoke all on function public.update_family_link_request(bigint, text) from public;
revoke all on function public.claim_family_link_request_email(bigint) from public;
revoke all on function public.mark_family_link_request_email_sent(bigint) from public;
revoke all on function public.release_family_link_request_email(bigint) from public;
revoke all on function public.list_family_link_requests() from anon;
revoke all on function public.update_family_link_request(bigint, text) from anon;
revoke all on function public.claim_family_link_request_email(bigint) from anon, authenticated;
revoke all on function public.mark_family_link_request_email_sent(bigint) from anon, authenticated;
revoke all on function public.release_family_link_request_email(bigint) from anon, authenticated;

grant execute on function public.submit_family_link_request(text, text, text, text, text) to anon, authenticated;
grant execute on function public.list_family_link_requests() to authenticated;
grant execute on function public.update_family_link_request(bigint, text) to authenticated;
grant execute on function public.claim_family_link_request_email(bigint) to service_role;
grant execute on function public.mark_family_link_request_email_sent(bigint) to service_role;
grant execute on function public.release_family_link_request_email(bigint) to service_role;
