-- Tables et règles d'accès pour l'onglet superadmin.
-- L'application peut lire les données de famille, mais seuls les comptes
-- inscrits dans public.superadmins peuvent les modifier.

create table public.superadmins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.superadmins enable row level security;
grant select on public.superadmins to authenticated;

create policy "Superadmin can verify own role"
  on public.superadmins
  for select
  to authenticated
  using (user_id = auth.uid());

create table public.family_data (
  id boolean primary key default true check (id is true),
  csv text not null,
  updated_at timestamptz not null default now()
);

alter table public.family_data enable row level security;
grant select on public.family_data to anon, authenticated;
grant insert, update on public.family_data to authenticated;

create policy "Anyone can read family data"
  on public.family_data
  for select
  to anon, authenticated
  using (true);

create policy "Superadmin can initialize family data"
  on public.family_data
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.superadmins s
      where s.user_id = auth.uid()
    )
  );

create policy "Superadmin can update family data"
  on public.family_data
  for update
  to authenticated
  using (
    exists (
      select 1 from public.superadmins s
      where s.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.superadmins s
      where s.user_id = auth.uid()
    )
  );

-- Exports versionnés : le premier students.csv reste inchangé, et chaque export
-- ajoute un snapshot v2, v3, etc. La fonction SQL active ce snapshot atomiquement.
create table public.family_data_versions (
  version_number bigint generated by default as identity (start with 2) primary key,
  csv text not null,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

alter table public.family_data_versions enable row level security;
grant select on public.family_data_versions to authenticated;

create policy "Superadmins can read archived family data"
  on public.family_data_versions
  for select
  to authenticated
  using (
    exists (
      select 1 from public.superadmins s
      where s.user_id = auth.uid()
    )
  );

create or replace function public.archive_family_data_version(p_csv text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  archived_version bigint;
begin
  if auth.uid() is null or not exists (
    select 1 from public.superadmins s
    where s.user_id = auth.uid()
  ) then
    raise exception 'Accès réservé au superadmin.' using errcode = '42501';
  end if;

  if p_csv is null or length(trim(p_csv)) = 0 then
    raise exception 'La nouvelle base est vide.' using errcode = '22023';
  end if;

  insert into public.family_data_versions (csv, created_by)
  values (p_csv, auth.uid())
  returning version_number into archived_version;

  insert into public.family_data (id, csv, updated_at)
  values (true, p_csv, now())
  on conflict (id) do update
  set csv = excluded.csv,
      updated_at = excluded.updated_at;

  return archived_version;
end;
$$;

revoke all on function public.archive_family_data_version(text) from public;
revoke all on function public.archive_family_data_version(text) from anon;
grant execute on function public.archive_family_data_version(text) to authenticated;

-- Après avoir créé ton utilisateur dans Authentication > Users,
-- remplace l'UUID ci-dessous par son ID, puis exécute cette ligne dans SQL Editor :
-- insert into public.superadmins (user_id) values ('REMPLACER_PAR_UUID') on conflict do nothing;
