-- À exécuter une fois dans Supabase SQL Editor.
-- Conserve chaque export comme version, sans remplacer students.csv d'origine.

create table if not exists public.family_data_versions (
  version_number bigint generated by default as identity (start with 2) primary key,
  csv text not null,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

alter table public.family_data_versions enable row level security;
grant select on public.family_data_versions to authenticated;

drop policy if exists "Superadmins can read archived family data" on public.family_data_versions;
create policy "Superadmins can read archived family data"
  on public.family_data_versions
  for select
  to authenticated
  using (
    exists (
      select 1 from public.superadmins s
      where s.user_id = auth.uid()
    )
  );

create or replace function public.archive_family_data_version(p_csv text)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  archived_version bigint;
begin
  if auth.uid() is null or not exists (
    select 1 from public.superadmins s
    where s.user_id = auth.uid()
  ) then
    raise exception 'Accès réservé au superadmin.' using errcode = '42501';
  end if;

  if p_csv is null or length(trim(p_csv)) = 0 then
    raise exception 'La nouvelle base est vide.' using errcode = '22023';
  end if;

  insert into public.family_data_versions (csv, created_by)
  values (p_csv, auth.uid())
  returning version_number into archived_version;

  insert into public.family_data (id, csv, updated_at)
  values (true, p_csv, now())
  on conflict (id) do update
  set csv = excluded.csv,
      updated_at = excluded.updated_at;

  return archived_version;
end;
$$;

revoke all on function public.archive_family_data_version(text) from public;
revoke all on function public.archive_family_data_version(text) from anon;
grant execute on function public.archive_family_data_version(text) to authenticated;
